### ISSUE TITLE
ModuleNotFoundError: No module named 'context_locals'

### ISSUE THREAD

**Issue by ghost** [mispchallenge/misp2022_baseline#12]
Hi, when I run `bash run_misp.sh -1` in the track2_AVDR, the following error was reported. I have tried different versions of tool, but this problem is still not solved.
```
local/prepare_dict.sh succeeded
Traceback (most recent call last):
  File "local/prepare_data.py", line 10, in <module>
    from tool.data_io import safe_load, safe_store
File "/miniconda3/envs/misp/lib/python3.7/site-packages/tool/__init__.py", line 11, in <module>
 from context_locals import app, local
ModuleNotFoundError: No module named 'context_locals'
```
How to solve this problem? Thank you for your answer.

**Comment by mispchallenge** [comment]
There's no need for you to install different versions of tool. In our folders, you can find the tool directory. I guess that there is a confict between the installed tool and the tool directory.

**Comment by ghost** [comment]
@mispchallenge Thanks for your answer. When I run `bash run_misp.sh 1`, 
```
Exception: jieba: file does not exist: /misp2022_baseline/track2_AVDR/data/local/dict/word_seg_vocab.txt
``` 
is this file missing？
